# Compiler and flags
CC = gcc
CFLAGS = -Wall -O2 -MD -Wno-unknown-pragmas
LDFLAGS = -lgmp -lssl -lcrypto -lbcrypt


# Target executable
TARGET = diffie-hellman.exe

# Source files
SRCS = diffie-hellman-example.c diffie-hellman.c

# Object files (auto from SRCS)
OBJS = $(SRCS:.c=.o)

# Dependency files (auto-generated by -MD)
DEPS = $(SRCS:.c=.d)

# Default rule
all: $(TARGET)

# Link the executable
$(TARGET): $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

# Include dependency files if they exist
-include $(DEPS)

# Clean up build artifacts
clean:
	@rm -f $(OBJS) $(DEPS) $(TARGET)
